[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]


[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I"]  # basics + import sorting
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
